name: 'Lint, format & test package when pushed or pulled to "main" branch'

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    check:
        runs-on: 'ubuntu-latest'
        steps:
            -   name: 'Get code'
                uses: 'actions/checkout@v4'
            -   name: 'Prepare package'
                run: |
                    python -m pip install --upgrade pip
                    pip install .[dev]
            -   name: 'Lint & format with ruff'
                run: |
                    ruff check
                    ruff format
            -   name: 'Run tests with pytest'
                run: |
                    pytest
