name: 'Release new version to PyPi'

on:
    release:
        types:
            - 'released'

jobs:
    release:
        runs-on: 'ubuntu-latest'
        steps:
            -   name: 'Get code'
                uses: 'actions/checkout@v4'
            -   name: 'Prepare python'
                run: |
                    python -m pip install --upgrade pip
                    pip install build
            -   name: 'Build package'
                run: |
                    python -m build
            -   name: 'Publish to PyPi'
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    password: ${{ secrets.PYPI_API }}
